[package]
name = "parquet2lance"
version = "0.2.0"
edition = "2021"
description = "Convert parquet files to lance"
repository = "https://github.com/haoxins/parquet2lance"
license-file = "LICENSE"
keywords = ["parquet", "lance", "object_store", "gcs"]

[dependencies]
arrow = { version = "37.0", features = ["prettyprint"] }
arrow-array = "37.0"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
lance = "0.4.6"
object_store = { version = "0.5", features = ["aws", "gcp"] }
parquet = "37"
rayon = "1"
tokio = { version = "1", features = ["full"] }
