[package]
name = "parquet2lance"
version = "0.4.1"
edition = "2021"
description = "Convert parquet files to lance"
repository = "https://github.com/haoxins/parquet2lance"
license-file = "LICENSE"
keywords = ["parquet", "lance", "object_store"]

[dependencies]
clap = { version = "4", features = ["derive"] }
futures = "0.3"
lance = "0.10"
object_store = { version = "0.9.0", features = ["aws", "azure", "gcp"] }
parquet = "50.0"
tokio = { version = "1", features = ["full"] }
