[package]
name = "_"
version = "0.6.0"
edition = "2024"
repository = "https://github.com/haoxins/parquet2lance"
publish = false

[lib]
name = "parquet2lance"
crate-type = ["cdylib"]

[dependencies]
parquet2lance = { path = "../rust" }
pyo3 = "0.25"
tokio = { version = "1", features = ["full"] }
