[package]
name = "p2l"
version = "0.3.5"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "parquet2lance"

[dependencies]
parquet2lance = { path = "../rust" }
pyo3 = "0.20"
tokio = { version = "1", features = ["full"] }
